export const dataTest = {
  message: "Lista de despesas",
  pagination: {
    totalItems: 6,
    itemsPerPage: 10,
    currentPage: 1,
    totalPages: 1,
  },
  data: [
    {
      id: 1,
      description: "Compra de materiais de escritório",
      month: 5,
      year: "2025",
      amount: 2215000,
      createdAt: "2025-05-12T13:17:34.988Z",
      updatedAt: null,
      supplierId: 1,
      secretaryId: 1,
      userId: 1,
      subsectorId: 1,
      supplierName: "Fornecedor Teste",
      subsectorName: "Recursos Humanos",
    },
    {
      id: 2,
      description: "Compra de materiais de escritório",
      month: 5,
      year: "2025",
      amount: 500,
      createdAt: "2025-05-12T13:18:13.628Z",
      updatedAt: null,
      supplierId: 1,
      secretaryId: 1,
      userId: 1,
      subsectorId: 1,
      supplierName: "Fornecedor Teste",
      subsectorName: "Recursos Humanos",
    },
    {
      id: 3,
      description: "Teste 2",
      month: 5,
      year: "2025",
      amount: 500,
      createdAt: "2025-05-12T18:13:44.631Z",
      updatedAt: null,
      supplierId: 1,
      secretaryId: 1,
      userId: 1,
      subsectorId: 2,
      supplierName: "Fornecedor Teste",
      subsectorName: "Recursos Humanos",
    },
    {
      id: 4,
      description: "Teste 3",
      month: 5,
      year: "2025",
      amount: 500,
      createdAt: "2025-05-12T18:13:50.434Z",
      updatedAt: null,
      supplierId: 1,
      secretaryId: 1,
      userId: 1,
      subsectorId: 3,
      supplierName: "Fornecedor Teste",
      subsectorName: "Recursos Humanos",
    },
    {
      id: 5,
      description: "Teste 3",
      month: 5,
      year: "2025",
      amount: 950000,
      createdAt: "2025-05-13T12:08:57.370Z",
      updatedAt: null,
      supplierId: 1,
      secretaryId: 1,
      userId: 1,
      subsectorId: 1,
      supplierName: "Fornecedor Teste",
      subsectorName: "Recursos Humanos",
    },
    {
      id: 6,
      description: "Aquisição de carga",
      month: 5,
      year: "2025",
      amount: 1257400,
      createdAt: "2025-05-13T12:10:56.928Z",
      updatedAt: null,
      supplierId: 1,
      secretaryId: 1,
      userId: 1,
      subsectorId: 1,
      supplierName: "Fornecedor Teste",
      subsectorName: "Recursos Humanos",
    },
    {
      id: 6,
      description: "Aquisição de carga",
      month: 5,
      year: "2025",
      amount: 1257400,
      createdAt: "2025-05-13T12:10:56.928Z",
      updatedAt: null,
      supplierId: 1,
      secretaryId: 1,
      userId: 1,
      subsectorId: 1,
      supplierName: "Fornecedor Teste",
      subsectorName: "Recursos Humanos",
    },
    {
      id: 6,
      description: "Aquisição de carga",
      month: 5,
      year: "2025",
      amount: 1257400,
      createdAt: "2025-05-13T12:10:56.928Z",
      updatedAt: null,
      supplierId: 1,
      secretaryId: 1,
      userId: 1,
      subsectorId: 1,
      supplierName: "Fornecedor Teste",
      subsectorName: "Recursos Humanos",
    },
    {
      id: 6,
      description: "Aquisição de carga",
      month: 5,
      year: "2025",
      amount: 1257400,
      createdAt: "2025-05-13T12:10:56.928Z",
      updatedAt: null,
      supplierId: 1,
      secretaryId: 1,
      userId: 1,
      subsectorId: 1,
      supplierName: "Fornecedor Teste",
      subsectorName: "Recursos Humanos",
    },
    {
      id: 6,
      description: "Aquisição de carga",
      month: 5,
      year: "2025",
      amount: 1257400,
      createdAt: "2025-05-13T12:10:56.928Z",
      updatedAt: null,
      supplierId: 1,
      secretaryId: 1,
      userId: 1,
      subsectorId: 1,
      supplierName: "Fornecedor Teste",
      subsectorName: "Recursos Humanos",
    },
  ],
};
